# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        # Artifact name
        name: 'JarFile'
        # Destination path
        path: /home/runner/work/mvn/mvn/my-app/target/my-app-1.0-SNAPSHOT-shaded.jar
